### ISSUE TITLE
Difference between this and chrisguttandin/standardized-audio-context

### ISSUE THREAD

**Issue by goatandsheep** [audiojs/audio-context#21]
should I use this repo or https://github.com/chrisguttandin/standardized-audio-context

**Comment by dy** [comment]
_audio-context_ is 300bytes thingy to manage audio-context in audio packages.
_standardized-audio-context_ is 30kb API justifying layer, sort of reliability provider/polyfill.
If you're going to build an app, for better cross-browser support pick standardized-audio-context.
For modules that need default audio-context or need web-audio, pick audio-context.
Ideally these two should not be mutually exclusive.

**Comment by goatandsheep** [comment]
Amazing description!! Thank you so much!

**Comment by chrisguttandin** [comment]
Hi @dy, hi @goatandsheep, it's correct that this library and standardized-audio-context could be used next to each other. I took great care to not patch any native prototype in standardized-audio-context which means it could even be used in libraries without worrying about any side effects. But as you already said standardized-audio-context is not the smallest library in the world. :-) However there are some things library authors can do to reduce the bundle size. I'm happy to explain that further if you want to build a library with it.
