### ISSUE TITLE
Transfer to audiojs?

### ISSUE THREAD

**Issue by dfcreative** [audiojs/audio-context#7]
Hi @juliangruber!

Thanks for the foundational package, we heavily use it in @audiojs.
Just a humble suggestion − since we are using it in so many dependent packages, and since you are the member of @audiojs − is there a sense to transfer the package there?
We will set greenkeeper and API docs for that. Of course you will be the owner of the package. The name perfectly fits to the naming of audio-* packages.

Cheers

**Comment by juliangruber** [comment]
makes very much sense! great suggestion, and moved :)
