### ISSUE TITLE
npm access?

### ISSUE THREAD

**Issue by dfcreative** [audiojs/audio-context#8]
@juliangruber

One more request.
I've updated readme and set up some infrastructural things − can you grant access for npm to publish update? If you don't mind.

```bash
npm owner add dfcreative audio-context
npm owner add jamen audio-context
```

Cheers,

**Comment by dfcreative** [comment]
Should we publish it @1.0.0 maybe?

**Comment by jamen** [comment]
that seems fine to me.  would need to update it everywhere though so we don't have `0.x` vs `1.x` installs of same code in different packages (not sure if that is problem w/ bundling?)

**Comment by dfcreative** [comment]
@jamen greenkeeper should take care of @audiojs packages, there is a lot of others though.

**Comment by juliangruber** [comment]
added both of you on npm

**Comment by dfcreative** [comment]
Done! Thanks.
